### ISSUE TITLE
Using download mode with only a workgroup causes an error

### ISSUE THREAD

**Issue by kanga333** [speee/go-athena#15]
## What

Athena allows you to omit the output-location specification if you specify a workgroup. However, since gzip/download mode parses the s3 bucket from the output-location, omitting the output-location will result in an error. 

If you create a client with the following settings

```go
db, _ := sql.Open("athena", "db=default&workgroup=primary&result_mode=dl")
```

I get the following error when executing a query

```
panic: runtime error: slice bounds out of range [5:0]

goroutine 40 [running]:
github.com/speee/go-athena.(*rowsDL).downloadCsv(0xc000484180, 0xc00026ea00, 0x0, 0x0, 0x1, 0x0)
        /work/dev/pkg/mod/github.com/speee/go-athena@v1.0.0/rows_dl.go:75 +0x519
github.com/speee/go-athena.(*rowsDL).downloadCsvAsync(0xc000484180, 0x1725700, 0xc000090480, 0xc0000904e0, 0xc00026ea00, 0x0, 0x0)
        /work/dev/pkg/mod/github.com/speee/go-athena@v1.0.0/rows_dl.go:70 +0x4c
created by github.com/speee/go-athena.(*rowsDL).init
        /work/dev/pkg/mod/github.com/speee/go-athena@v1.0.0/rows_dl.go:46 +0x12d
exit status 2
```

If only a workgroup is specified, it is better to parse the s3 bucket from the workgroup configuration.

**Comment by muroon** [comment]
Great! Thank you for raising the issue.
